version: "3"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "mysql"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json"
      - "./rabbitmq/data:/var/lib/rabbitmq/mnesia/"
      - "./rabbitmq/logs:/var/log/rabbitmq/log"
    container_name: "rabbitmq"
    restart: "always"
    networks:
      - "backend"

  redis:
    image: "redis:alpine"
    hostname: "redis"
    ports:
      - "6379:6379"
    volumes:
      - "./redis:/data"
    container_name: "redis"
    restart: "always"
    networks:
      - "backend"

  mysql:
    image: "mysql:5.7"
    hostname: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "happyday"
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/my.cnf:/etc/my.cnf"
    ports:
      - "3306:3306"
    networks:
      - "backend"
    restart: "always"
    container_name: "mysql"

networks:
  "backend":

  