version: '3'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
  app:
    container_name: my-app
    build:
      context: .
      dockerfile: Dockerfile
    image: app:latest
    expose:
      - 8080
    ports:
      - "18080:8080"
    depends_on:
      - "mysql"
    links:
      - "mysql:mymysql"