version: "3"
services:
  redis:
    image: "redis:alpine"
    hostname: "redis"
    ports:
      - "6379:6379"
    container_name: "redis20210131"
    restart: "always"
    networks:
      - "backend"
  eureka-server:
    image: "huskyui/eureka-server:latest"
    hostname: "eureka-server"
    ports:
    - "8888:8888"
    container_name: "eureka"
    restart: "always"
    networks:
      - "backend"
    depends_on:
      - "redis"
  service-center:
    image: "huskyui/service-center:latest"
    hostname: "service-center"
    ports:
      - "8081:8081"
    container_name: "service-center"
    restart: "always"
    networks:
      - "backend"
    depends_on:
      - "eureka-server"
networks:
  "backend":