spring:
  datasource:
    url: jdbc:mysql://mymysql:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    username: root
    password: root